#!/usr/bin/env bash
# Reproducible local install for the SAM 2.1 Tiny grounding runner
# (harness/scripts/sam2-runner.py, harness/lib/sam2-tiny.ts's pi.sam2.1-tiny/v1
# protocol). Everything this writes is machine-local and gitignored by
# location — nothing here is committed. Safe to re-run; each step is
# idempotent and skips work already done correctly.
#
# Usage: harness/scripts/install-sam2-runner.sh [install_dir]
#   install_dir defaults to ~/LLM/sam2-tiny
set -euo pipefail

INSTALL_DIR="${1:-$HOME/LLM/sam2-tiny}"
CHECKPOINT="$INSTALL_DIR/sam2.1_hiera_tiny.pt"
CHECKPOINT_URL="https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_tiny.pt"
CHECKPOINT_SHA256="7402e0d864fa82708a20fbd15bc84245c2f26dff0eb43a4b5b93452deb34be69"
VENV="$INSTALL_DIR/venv"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNNER="$HERE/sam2-runner.py"

mkdir -p "$INSTALL_DIR"

# Prefer 3.12/3.13: torch.jit.script (imported transitively by sam2) logs a
# FutureWarning on 3.14+ ("not supported ... may break"). The runner is
# verified working on 3.14 too (measured, 2026-09) — this is hardening
# against a future break, not a fix for one observed today.
PYTHON=""
for candidate in python3.12 python3.13 python3; do
	if command -v "$candidate" >/dev/null 2>&1; then PYTHON="$candidate"; break; fi
done
[ -n "$PYTHON" ] || { echo "no python3 found on PATH" >&2; exit 1; }
if [ "$PYTHON" = "python3" ]; then
	ver="$($PYTHON -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")')"
	case "$ver" in
		3.12|3.13) ;;
		*) echo "warning: using python3 ($ver); python3.12/3.13 not found on PATH — preferred but not required" >&2 ;;
	esac
fi

if [ ! -x "$VENV/bin/python" ]; then
	echo "creating venv ($PYTHON) at $VENV"
	"$PYTHON" -m venv "$VENV"
else
	echo "venv already exists at $VENV"
fi

echo "installing torch + sam2==1.1.0 + pillow + numpy (idempotent)"
# A venv created by uv (as an earlier ad-hoc install here was) has no pip
# seeded at all — ensurepip is the portable bootstrap regardless of how the
# venv was made; -m pip (not the bin/pip shim) works either way afterward.
"$VENV/bin/python" -m ensurepip --upgrade >/dev/null 2>&1 || true
"$VENV/bin/python" -m pip install --quiet --upgrade pip
"$VENV/bin/python" -m pip install --quiet torch pillow numpy "sam2==1.1.0"

if [ -f "$CHECKPOINT" ] && [ "$(shasum -a 256 "$CHECKPOINT" | cut -d' ' -f1)" = "$CHECKPOINT_SHA256" ]; then
	echo "checkpoint already installed and verified: $CHECKPOINT"
else
	echo "fetching checkpoint (156 MB) from $CHECKPOINT_URL"
	curl -fL --progress-bar -o "$CHECKPOINT.partial" "$CHECKPOINT_URL"
	actual="$(shasum -a 256 "$CHECKPOINT.partial" | cut -d' ' -f1)"
	if [ "$actual" != "$CHECKPOINT_SHA256" ]; then
		rm -f "$CHECKPOINT.partial"
		echo "checkpoint SHA-256 mismatch: expected $CHECKPOINT_SHA256, got $actual — refusing to install an unverified checkpoint" >&2
		exit 1
	fi
	mv "$CHECKPOINT.partial" "$CHECKPOINT"
	echo "checkpoint verified and installed: $CHECKPOINT"
fi

cat > "$INSTALL_DIR/run.sh" <<RUNEOF
#!/usr/bin/env bash
# Generated by install-sam2-runner.sh — do not edit; re-run the installer instead.
export PI_SAM2_CHECKPOINT="$CHECKPOINT"
exec "$VENV/bin/python" "$RUNNER"
RUNEOF
chmod +x "$INSTALL_DIR/run.sh"

echo
echo "done. Set in your pi environment:"
echo "  VISION=on VISION_GROUNDING=sam PI_SAM2_COMMAND=$INSTALL_DIR/run.sh"
